apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-vxkn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-vxkn
    app.kubernetes.io/part-of: tkrw-pr712-0075-0055-app
  name: devfile-sample-vxkn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-vxkn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-vxkn
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0055-tenant/tkrw-pr712-0075-0055-app/devfile-sample-vxkn@sha256:ffca0d89e997cf5ceaa52a651aabef94f380b1a6363f111460f10386e7cd1f3b
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
